# Site settings
title: Cataliso
email: info@cataliso.com
description: > # this means to ignore newlines until "baseurl:"
 Professional blog for Ananth Vasishta on product, product management, product strategy, entrepreneurship and startups.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cataliso.com" # the base hostname & protocol for your site
twitter_username: cataliso

# Build settings
markdown: kramdown
